server:
  port: 8002

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: lb://student
          predicates:
            - Path=/api/v1/**
        - id: school
          uri: lb://school
          predicates:
            - Path=/api/v1/**
#  eureka:
#    instance:
#      instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
#      prefer-ip-address: true
#    client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka/