server:
  port: 8001

spring:
  application:
    name: school
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 10  # Adjust as needed
#    lease-expiration-duration-in-seconds: 30  # Adjust as needed
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


## Spring Boot Application Name
#spring.application.name=school
#
## Spring Cloud Config Server
#spring.config.import=optional:configserver:http://localhost:8888
#
## Eureka Configuration
#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
#eureka.instance.prefer-ip-address=true
##eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
## Server Port
#server.port=8001
#
## PostgreSQL Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/school
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA Hibernate Configuration
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#spring:
#  application:
#    name: school
#
#  config:
#    import: optional:configserver:http://localhost:8888
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/school
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 10   # Adjust as needed
#    lease-expiration-duration-in-seconds: 30   # Adjust as needed
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#
#server:
#  port: 8001
